apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "56.21.4"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: Create
  values:
    prometheus:
      serviceMonitor:
        enabled: false
      podMonitor:
        enabled: false
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}

    grafana:
      defaultDashboardsEnabled: true
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          folder: CloudNativePG
          folderAnnotation: grafana_folder
          searchNamespace: ALL
      dashboardsConfigMaps:
        CloudNativePG:
          - grafana-dashboard-cloudnativepg
