apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "56.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
  values:
    grafana:
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          folder: CloudNativePG
          labelValue: "1"
          searchNamespace: ALL
      dashboardsConfigMaps:
        - grafana-dashboard-cloudnativepg
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
