apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: phoenix-app
  namespace: phoenix
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: "1.0"
