apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: slack-notifications
  namespace: flux-system
spec:
  interval: 1m
  path: ./notifications/slack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  dependsOn:
    - name: flux-system
