apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: flux-alert
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: dev-cluster
      namespace: flux-system
    - kind: Kustomization
      name: flux-system
      namespace: flux-system
    - kind: GitRepository
      name: flux-system
      namespace: flux-system