apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: gitops-receiver
  namespace: flux-system
spec:
  type: generic
  resources:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: dev-cluster
      namespace: flux-system
  secretRef:
    name: slack-webhook-secret
