apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgres
  namespace: postgresql
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  # enablePodMonitor: true
  storage:
    storageClass: standard
    size: 1Gi
  superuserSecret:
    name: pg-superuser-secret
