apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infrastructure/helm-repos/cloudnativepg-repo.yaml
  - ../../infrastructure/helm-repos/prometheus-repo.yaml
  
  - ./monitoring-kustomizations.yaml

  - ../../apps/overlays/dev/hello-world
  - ../../notifications/slack
  - ../../apps/overlays/dev/phoenix-app

  # Add new Kustomizations
  - ./postgres-namespace.yaml
  - ./cloudnativepg.yaml
  - ./postgres-cluster.yaml

  - ../../secrets