# clusters/dev-cluster/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/base/cloudnativepg
  -  ../../apps/base/postgres-cluster

  - ../../apps/base/monitoring
  - ../../apps/overlays/dev/hello-world

  - ../../infrastructure/helm-repos/cloudnativepg-repo.yaml
  - ../../infrastructure/helm-repos/prometheus-repo.yaml

  - ../../secrets
  # - ../../notifications/slack

  - ../../apps/overlays/dev/phoenix-app
