apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/base/monitoring        # HelmRelease for kube-prometheus-stack lives here
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m0s
  healthChecks:
    - kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/base/monitoring/config  # Contains PodMonitor/ServiceMonitor/PrometheusRule
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: monitoring-stack
  wait: true
  timeout: 10m0s
