apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phoenix-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "phoenix-app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "phoenix-app.fullname" . }}
    spec:
      containers:
        - name: phoenix
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: phoenix-config
            - secretRef:
                name: {{ .Values.secretRef }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
